EXPT_NAME theanolm-100k
EXPT_PARAMS expt10-seq15
EXPT_WORK_DIR /scratch/work/moisioa3/conv_lm/experiments/theanolm-100k/expt10-seq15
Experiment: theanolm-100k/expt10-seq15
Job ID: 54662087
Task ID: 
Host: gpu26.int.triton.aalto.fi
Start date: Thu Jul  9 13:03:21 EEST 2020
Work directory: /scratch/work/moisioa3/conv_lm/experiments/theanolm-100k/expt10-seq15
Temporary directory: /tmp/54662087

Currently Loaded Modules:
  1) anaconda3/latest   2) cuda/10.0.130   3) cudnn/7.4.2-cuda

 

floatX=float32,device=gpu,base_compiledir=/tmp/theano,exception_verbosity=high,openmp=False
Traceback (most recent call last):
  File "/scratch/work/groszt1/envs/theanoLM/bin/theanolm", line 4, in <module>
    __import__('pkg_resources').run_script('TheanoLM==1.3.2', 'theanolm')
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/EGG-INFO/scripts/theanolm", line 11, in <module>
    from theanolm.backend import NumberError, TheanoConfigurationError
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/theanolm/__init__.py", line 7, in <module>
    from theanolm.vocabulary import Vocabulary
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/theanolm/vocabulary/__init__.py", line 6, in <module>
    from theanolm.vocabulary.vocabulary import Vocabulary
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/theanolm/vocabulary/vocabulary.py", line 10, in <module>
    import theano
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/__init__.py", line 88, in <module>
    from theano.configdefaults import config
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/configdefaults.py", line 137, in <module>
    in_c_key=False)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/configparser.py", line 287, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/configparser.py", line 335, in __get__
    self.__set__(cls, val_str)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/configparser.py", line 346, in __set__
    self.val = self.filter(val)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/configdefaults.py", line 116, in filter
    'You are tring to use the old GPU back-end. '
ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda* now. See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 for more information.
